### ISSUE TITLE
🐛 Bug report - Demo page

### ISSUE THREAD

**Issue by DilemmaGX** [Nightre/sparkle.js#1]
Founded a bug on [demo page](https://nightre.github.io/sparkle.js/demo/chrome-dino/), occasionally, the game will be stuck at the restart menu, after clicking the "restart", the game will fail after one frame and play the fail sound effect.

**Comment by Gtd232** [comment]
你好!看起来你是会说中文的人?  
@Nightre 英文并不好!使用中文可更准确地向他表述.

**Comment by Nightre** [comment]
谢谢你！我待会看！！
